"""
Keep the published write-up's chart honest.

docs/index.html carries one hard number set: the deviation chart's data array.
Everything else on that page is prose. This script rewrites that array from
outputs/lab.json so the page cannot quietly drift away from what the code
actually prints -- the same reason the dashboard reads lab.json rather than
holding its own copy.

    python python/run_demo.py       # writes outputs/lab.json
    python python/sync_writeup.py   # pushes the numbers into docs/index.html
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LAB = ROOT / "outputs" / "lab.json"
PAGE = ROOT / "docs" / "index.html"

BEGIN = "/* SYNC:rows BEGIN -- generated by python/sync_writeup.py */"
END = "/* SYNC:rows END */"

# Long labels wrap badly in the chart gutter.
SHORT = {
    "Dense query-document similarity": "Dense query-doc similarity",
    "Referring root domains (log)": "Referring root domains",
    "Knowledge-graph entity coverage": "KG entity coverage",
    "Keyword density": "Keyword density  (truth 0)",
}

TOP, RH, PAD = 34, 27, 35


def build_rows(lab: dict) -> tuple[str, int]:
    rows = sorted(lab["calibration"]["rows"], key=lambda r: -r["true"])
    lines = []
    width = max(len(SHORT.get(r["label"], r["label"])) for r in rows) + 3
    for r in rows:
        label = SHORT.get(r["label"], r["label"])
        lines.append(
            f'  [{(chr(34) + label + chr(34) + ",").ljust(width)}'
            f'{r["true"]:.3f}, {r["naive"]:.3f}, {r["corrected"]:.3f}],')
    return "\n".join(lines), len(rows)


def main() -> None:
    lab = json.loads(LAB.read_text(encoding="utf-8"))
    html = PAGE.read_text(encoding="utf-8")
    body, n = build_rows(lab)

    block = f"{BEGIN}\nconst rows = [\n{body}\n];\n{END}"

    if BEGIN in html:
        html = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block,
                      html, flags=re.S)
    else:
        html = re.sub(r"const rows = \[.*?\];", block, html, count=1, flags=re.S)

    height = TOP + n * RH + PAD
    html = re.sub(r'(<svg id="dev" viewBox="0 0 740 )\d+(")',
                  rf"\g<1>{height}\g<2>", html)

    PAGE.write_text(html, encoding="utf-8")
    print(f"synced {n} rows into docs/index.html, viewBox height {height}")


if __name__ == "__main__":
    main()
